---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: tekton-kueue
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: tekton-kueue
    app.kubernetes.io/managed-by: kustomize
  name: webhook
  namespace: system
