kind: Kustomization
images:
- name: controller
  newName: konflux-ci/tekton-kueue
  newTag: latest
resources:
- deployment.yaml
- manifests.yaml
- service.yaml
- default-priority-class.yaml

configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1

configMapGenerator:
- name: config
  files:
  - config.yaml
